title: 'Minimal Doc Product'
description: 'A sample documentation product.'
google-site-verification:
application-name: 'Vonage Minimal Doc Product APIs'
og-image: vbc-card.png
og-image-width: 835
og-image-height: 437
